### ISSUE TITLE
Too many DLL's

### ISSUE THREAD

**Issue by limelect** [a3sma/PussyCommander#2]
Too many dll's, without a source.
What do they do?
I will not use this software without any of the DLL source

**Comment by a3sma** [comment]
Hello!
1. sqlite3.dll uses to open DameWare sqlite file witch stores connections settings, and injects into it needed information. If you not using DameWare connections you can delete it. 
2. All other dll's are from firebird 3 and using to connect main database and settigs database.

They are all open source and you can find and recompile it by yourself.

Thanks for reply!

**Comment by limelect** [comment]
Thanks
